version: '3'

services:
  otrs:
    image: juanluisbaptiste/otrs:latest
    ports:
      - '8080:8080'
    # If running behind a proxy container, expose the ports instead
    # and link the proxy container to this one.
    #  expose:
    #  - "80"
    depends_on:
      - mariadb
      # Descomentar caso utilize o PostFix
      - postfix
    env_file: otrs.env
    volumes:
      - './volumes/config:/opt/otrs/Kernel'
      # Uncomment if using OTRS_ARTICLE_STORAGE_TYPE=ArticleStorageFS
      #- ./volumes/article:/opt/otrs/var/article
      - ./volumes/skins:/opt/otrs/var/httpd/htdocs/skins/
      - ./backups:/var/otrs/backups
      - ./volumes/addons:/opt/otrs/addons
      - ./volumes/db_upgrade:/opt/otrs/db_upgrade
      - /etc/localtime:/etc/localtime:ro
# Serviço de configuração maridadb(MySQL)
  mariadb:
    image: juanluisbaptiste/otrs-mariadb:latest
    ports:
      - '3306:3306'
    expose:
      - "3306"
    env_file: otrs.env
    volumes:
      - ./volumes/mysql:/var/lib/mysql
      - /etc/localtime:/etc/localtime:ro
# Serviço de configuração do Postfix
  postfix:
     image: juanluisbaptiste/postfix:latest
     ports:
       - '25:25'
     expose:
       - '25'
       